on: [push]
name: CLI_Test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

### insert here       
    - name: Get Publish Profile
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          test=$(az webapp deployment list-publishing-credentials --name zodiac-web --resource-group zodiac-rg)
          echo $test
