on: [push]
env:
  WEB_APP_NAME: zodiac-web
  HOSTiNG_PLAN_NAME: zodiac-web-plan
  AI_LOCATION: UK South
  SKU: S1 Standard
  DB_SERVER_NAME: zodiac-db-server
  DB_USER: dbadmin
  DB_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
  DB_LOCATION: UK South
  DB_NAME: zodiac-web-db
  LIMONE_BASE_URL: https://zodiac-limone-api.azurewebsites.net/   

name: CLI_Test

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/deployment_scripts/test.sh
          $GITHUB_WORKSPACE/deployment_scripts/test.sh $WEB_APP_NAME arg2
       
