on: [push]
name: CLI_Test
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v1

    - name: Azure CLI script file
      env:
        GITHUB_ROOT_NAME: zodiac
        GITHUB_LOCATION: uksouth
        GITHUB_SKU: S1 Standard
        GITHUB_DB_USER: dbadmin
        GITHUB_DB_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
        GITHUB_LIMONE_BASE_URL: https://zodiac-limone-api.azurewebsites.net/   
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          chmod +x $GITHUB_WORKSPACE/deployment_scripts/test.sh
          $GITHUB_WORKSPACE/deployment_scripts/test.sh 
       
