on:
  push:
    paths:
    - sirmione-web/Application/Sirmione.Web/**

name: CLI_Test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Build with dotnet
      run: dotnet build sirmione-web/Application/Sirmione.Web/Sirmione.Web.csproj --configuration Release

    - name: dotnet publish
      run: |
        dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp 
        
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - run: publishProfile=$(az webapp deployment list-publishing-credentials --name zodiac-web --resource-group zodiac-rg)

 #   - name: Azure CLI script file
 #     env:
 #       GITHUB_ROOT_NAME: zodiac
 #       GITHUB_LOCATION: uksouth
 #       GITHUB_SKU: S1 Standard
 #       GITHUB_DB_USER: dbadmin
 #       GITHUB_DB_PASSWORD: ${{ secrets.DB_ADMIN_PASSWORD }}
 #       GITHUB_LIMONE_BASE_URL: https://zodiac-limone-api.azurewebsites.net/   
 #     uses: azure/CLI@v1
 #     with:
 #       azcliversion: latest
 #       inlineScript: |
 #         chmod +x $GITHUB_WORKSPACE/deployment_scripts/test.sh
 #         $GITHUB_WORKSPACE/deployment_scripts/test.sh        
    
    
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: sirmione-web # Replace with your app name
        publish-profile: $publishProfile # Define secret variable in repository settings as per action documentation
        package: ${{env.DOTNET_ROOT}}/myapp 
