name: Deploy Generator 
env:
   DEFAULT_LOCATION: uksouth
   ZODIAC_GENERATOR_ALIAS: zodgenz

#on:
#  push:
#    paths:
#    - Zodiac.Generator/**

on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Docker Login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{env.ZODIAC_GENERATOR_ALIAS}}.azurecr.io
        username: ${{env.ZODIAC_GENERATOR_ALIAS}}acr
        password: ${{ secrets.ACR_PASSWORD }}
        
    - name: Run Deployment Scripts
      run: | 
             ls
             cd Zodiac.Generator
             ls
             cd ..

    - name: 'Compose Customized Docker Image'
      shell: bash
      run: |
        # If your function app project is not located in your repository's root
        # Please change the path to your directory for docker build
        #pushd Zodiac.Generator
        docker build ./Zodiac.Generator -t ${{env.ZODIAC_GENERATOR_ALIAS}}.azurecr.io/zodiac/generator:${{github.run_number}}
        docker push ${{env.ZODIAC_GENERATOR_ALIAS}}.azurecr.io/generator/zodiac/generator${{github.run_number}}
        #popd

    - name: 'Run Azure Functions Container Action'
      uses: Azure/functions-container-action@v1
      id: fa
      with:
        app-name: ${{env.ZODIAC_GENERATOR_ALIAS}}-func
        image: ${{env.ZODIAC_GENERATOR_ALIAS}}.azurecr.io/zodiac/generator:${{github.run_number}}
    
    - name: Azure logout
      run: |
        az logout

# For more information on GitHub Actions:
#   https://help.github.com/en/categories/automating-your-workflow-with-github-actions
