on:
  push:
    paths:
    - global/**
 
name: Deploy Infrastructure
env:
  DEFAULT_LOCATION: ${{ secrets.DEFAULT_LOCATION }}
  SIRMIONE_ALIAS: ${{ secrets.SIRMIONE_ALIAS }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
    
      - name: Test printing your secret (Remove this step in production)
        run: |
                chmod +x .github/workflows/experiment.sh
                source .github/workflows/experiment.sh
                
      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
        dotnet-version: 3.1.101
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
   
    - 
