name: Scorpio-api

on:
  push:
    paths:
    - scorpio-api/Application/**
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build scorpio-api/Application/scorpio-api.csproj --configuration Release
