name: Sirmione-Web
env:
  WEB_SITE_NAME: zodiac
  LIMONE_BASE_URL: https://zodiac-limone-api.azurewebsites.net/   

on:
  push:
    paths:
    - sirmione-web/Application/Sirmione.Web/**
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build sirmione-web/Application/Sirmione.Web/Sirmione.Web.csproj --configuration Release
      
  
